### ISSUE TITLE
Support latest @11ty/eleventy

### ISSUE THREAD

**Issue by xander-marjoram** [kentaroi/eleventy-plugin-clean#4]
Hello, firstly thanks for creating and maintaining this package.

I was wondering if there were any plans to publish a new release which supports `@11ty/eleventy@2.0.1`, or if you are waiting for the next minor version before publishing an update?

Many thanks

**Comment by techbridgedev** [comment]
At this point, I'd be happy to see support for 11ty 3.x too.

**Comment by rediris** [comment]
I've added a PR here: https://github.com/kentaroi/eleventy-plugin-clean/pull/5

Hopefully @kentaroi will see this and consider merging it for an updated release.

**Comment by kentaroi** [comment]
I apologise for the delay in responding to your comments and the issue.
Thank you for letting me know, @xander-marjoram, @techbridgedev!!
Thank you very much for sending the pull request, @rediris!!
I have released it as 1.2.6.

**Comment by chromadesign** [comment]
Is support for Eleventy 3.x planned as well? Thanks!

**Comment by kentaroi** [comment]
Thank you for letting me know, @chromadesign!

Yes, I am planning to support Eleventy 3.x.

**Comment by seezee** [comment]
Unable to get this to work using either of the import methods.

**Comment by kentaroi** [comment]
@seezee 
If you find a bug in the plugin, please create a new issue including logs or error messages and the versions of Node.js, Eleventy, and eleventy-plugin-clean.
